name: Build, Generate Documentation, and Deploy

on:
  push:
    branches:
      - main  # Assuming you want to run this workflow on pushes to main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


#    - name: Setup MSBuild Path
#      uses: microsoft/setup-msbuild@v1.3.1

#    - name: Restore NuGet Packages
#      run: msbuild /t:restore

#    - name: Build Solution
#      run: msbuild /p:Configuration=Release


    - name: Install DocFX
      run: choco install docfx -y

    - name: Generate Documentation
      run: |
        docfx ./docfx/docfx.json

#    - name: Move Documentation to Subfolder
#      run: |
#        mkdir -p ./_site/root/AccuLadder
#        cp -r ./_site/* ./_site/root/AccuLadder/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docfx/_site  # Adjust if your DocFX output directory is different
